### ISSUE TITLE
Map function

### ISSUE THREAD

**Issue by abinici** [telperiontech/angular-rest#4]
Hi, currently I am using the following library for building api clients:

https://github.com/troyanskiy/ngx-resource

But this library is no longer maintained, so I am looking for an alternative. And your library looks very promising, it has all the features I am looking for, so I am considering to use your library.

But I have a question. When I make an api call and get a result, I need to change / map the result data. For instance, I need to change the date I get from the server from iso string to an object type called DateTime. Is it possible to change the data that comes from the api call? Can I use handler for this?

**Comment by alisahinozcelik** [comment]
hi @abinici, thank you  yes there is, you may use 'Handlers' for that.

there are several ways to use them.

For example:
```typescript
@Injectable()
@Client<SessionClient>()
export class SessionClient {
  private static tokenParser(original: HttpResponse<LoginResponse>, current: LoginResponse): LoginResponse {
    return {token: 'Bearer ' + current.token};
  }

  constructor(inject: Injector) {}

  @ErrorHandler()
  private static forbiddenMapper(original: HttpErrorResponse) {
    if (original.status === StatusCodes.FORBIDDEN) {
      throw new HttpErrorResponse({
        ...original,
        url: original.url ?? undefined,
        status: StatusCodes.BAD_REQUEST,
        statusText: getReasonPhrase(StatusCodes.BAD_REQUEST)
      });
    }
  }

  @Post('login')
  @Handlers<SessionClient>([SessionClient.tokenParser, SessionClient.forbiddenMapper])
  @Guards<SessionClient>(UnAuthorizedGuard)
  public loginRequest(@Body() body: LoginRequest): Promise<LoginResponse> {
    return null!;
  }
}

```
